// Code generated by MockGen. DO NOT EDIT.
// Source: cargo_toml_discovery.go

// Package mock_rust is a generated GoMock package.
package mock_rust

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDiscoverer is a mock of Discoverer interface.
type MockDiscoverer struct {
	ctrl     *gomock.Controller
	recorder *MockDiscovererMockRecorder
}

// MockDiscovererMockRecorder is the mock recorder for MockDiscoverer.
type MockDiscovererMockRecorder struct {
	mock *MockDiscoverer
}

// NewMockDiscoverer creates a new mock instance.
func NewMockDiscoverer(ctrl *gomock.Controller) *MockDiscoverer {
	mock := &MockDiscoverer{ctrl: ctrl}
	mock.recorder = &MockDiscovererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscoverer) EXPECT() *MockDiscovererMockRecorder {
	return m.recorder
}

// DiscoverCargoToml mocks base method.
func (m *MockDiscoverer) DiscoverCargoToml(path string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiscoverCargoToml", path)
	ret0, _ := ret[0].([]string)
	return ret0
}

// DiscoverCargoToml indicates an expected call of DiscoverCargoToml.
func (mr *MockDiscovererMockRecorder) DiscoverCargoToml(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiscoverCargoToml", reflect.TypeOf((*MockDiscoverer)(nil).DiscoverCargoToml), path)
}
